### PR TITLE
WIP: add Py3k patch 

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This adds (hopefully) py3k support to ecmwf_grib to at least linux. MacOSX should work, but this needs to be proved. The patch was created locally.

Reading and writing data files is working. I tested the examples locally on linux. I didn't check all this because of https://github.com/conda-forge/python-eccodes-feedstock/pull/1.

There might be some glitches left, so testing is welcome

Most necessary tweaks for the swig intermediate file were applied from https://github.com/pygraphviz/pygraphviz.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Would it be a problem, if we take the latest `1.15.0` gribapi? I made the patch against this one.

**Comment by ocefpaf** [comment]
> @ocefpaf Would it be a problem, if we take the latest `1.15.0` gribapi? I made the patch against this one.

Not at all.

**Comment by ocefpaf** [comment]
@kmuehlbauer `ecmwf` is in the channel but I guess `py3k` still needs some work :unamused: 

``` shell
checking whether numpy is installed... no
configure: error: NumPy is not installed. Use --disable-numpy if you want to disable Numpy from the build.
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/python-ecmwf_grib-feedstock/recipe/build.sh
```

Let me know if I can help.

**Comment by kmuehlbauer** [comment]
@ocefpaf Yeah, we should use `cmake` here also. The patch is for the cmake build. I'll have a look if I can do this right now.

**Comment by ocefpaf** [comment]
> @ocefpaf Yeah, we should use `cmake` here also. The patch is for the cmake build. I'll have a look if I can do this right now.

No rush.

@pelson once this works is it worth adding `ecmwf_grib` to the py3k `iris` builds again?

**Comment by kmuehlbauer** [comment]
@ocefpaf

> No rush.

This was easy, I think :grin: 

> @pelson once this works is it worth adding ecmwf_grib to the py3k iris builds again?

I'm not absolutely sure, that I catched everything. We have to check the binary_message stuff, b/c I encountered py3k string/byte-encoding problems there. But, and that's the good news, reading and writing works (I checked every example within eccodes, which is very much the same). Maybe @Qulogic can have a look at that patch for flaws and/or enhancements. Anyway, testing is appreciated.

**Comment by ocefpaf** [comment]
> Maybe @Qulogic can have a look at that patch for flaws and/or enhancements. Anyway, testing is appreciated.

:+1: 

Once this is merged I will do some testing locally and let you known. Thanks for the effort to bring `ecmwf_grib` to Python 3!

**Comment by QuLogic** [comment]
It's been a long time since I did that, so I can't really say if you've missed anything. I kind of wish I had seen that pygraphviz thing before because getting `FILE` to work was a bear.

One thing I did see is that you replaced `long` with `int` in the type checks, but that means you can no longer pass `long` on Python 2, breaking the API a little bit. In my original patch, I did a `int_types = (int, long)` or `int_types = (int, )` for 2 vs. 3 that's added to the other type tuples.

**Comment by kmuehlbauer** [comment]
@QuLogic Thanks for your  he long/comment. You're right, the long/int need to be addressed when this is applied upstream. So here it it is just applied to py3k. 

I did a extensive research about swig, python 3 and read hundreds of related and unrelated online resources. The pygraphviz solution is a good starting point but needed adaption for eccodes as well as gribapi.  At least I now have some knowledge about swig bindings.

**Comment by kmuehlbauer** [comment]
@ocefpaf Travis picked up the wrong python (2.7 from System). No idea, where to fix this. I changed cmake findPython in eccodes. Might do this here too.

**Pull request merged**
