### PR TITLE
Update to 1.19.0 release

### PR DESCRIPTION
**Pull request by kynan**
This also drops Python 3 support.

### CODE REVIEW

**Comment by kynan** [comment]
Circle again hasn't kicked off...

**Comment by kmuehlbauer** [comment]
Let me try something...

**Comment by kmuehlbauer** [comment]
@kynan I think I have the correct way of doing...

You'll need to login to Circle again, then do not go to conda-forge, but your own handle. Activate builds on your fork there. Then make another dummy commit here. This way I got #15 running...

**Comment by kynan** [comment]
@kmuehlbauer OK, I'll try that.

**Comment by kmuehlbauer** [comment]
@kynan That, did the trick!

**Comment by jakirkham** [comment]
So this should have gotten a re-rendering too. This should happen any time the `skip` changes. As a result, we are seeing problems in PR ( https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/12 ) from builds in the matrix that should not exist. Added PR ( https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/17 ) to re-render the feedstock so as to remove these unused matrix builds.

cc @jjhelmus

**Comment by kmuehlbauer** [comment]
@jakirkham Absolutely!

**Pull request merged**
