### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Something in the build requirements list has a short prefix.  Investigating...

**Comment by jjhelmus** [comment]
It is ecmwf_grid:

```
# conda inspect prefix-lengths /opt/conda/pkgs/*.tar.bz2
Packages with binary prefixes shorter than 255 characters:
/opt/conda/pkgs/ecmwf_grib-1.15.0-1.tar.bz2 (80 chars)
```

version `1.16.0` has been rebuilt with a long prefix but `1.15.0` has not.  Does it make sense to update this recipe to version `1.16.0`?  Or should a long prefix build of `ecmwf_grib` be created?

**Comment by kynan** [comment]
The latest release is 1.19.0, so it would make sense to update to the latest, yes.

**Comment by kynan** [comment]
That was done in #14. Do you want to rebase on master?

**Comment by jjhelmus** [comment]
PR has been rebased to pick up version `1.19.0`.  Thanks @kynan for updating this.

**Comment by kmuehlbauer** [comment]
@jjhelmus Thanks for rebasing. There is some issue with the prefix length in mac-osx. Do you have an idea which package(s) haven't been converted to long prefix? I suspect `jinja2`.

Also it seems, that the build was skipped on osx. Any ideas why this is happening?

**Comment by jjhelmus** [comment]
The issue with the the OS X build has nothing to do with the prefix length.  Rather the Python 3 build are [explicitly skipped in the recipe](https://github.com/conda-forge/python-ecmwf_grib-feedstock/blob/master/recipe/meta.yaml#L14) but the test script is still trying to check the produced  package(s) for a prefix length.  Since no packages are produced for Python 3 these builds fail.

It should be fine to merge this with the failing Python 3 builds, although  add Python 3 support back into the package would be preferred.

**Comment by jakirkham** [comment]
Could you please rebase this on PR ( https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/17 ) or after it is merged? I think that should fix the problem.

**Comment by jakirkham** [comment]
Went ahead and cherry-picked this into a new PR ( https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/18 ). @jjhelmus , could you please take a look and make sure it is correct?

**Comment by kynan** [comment]
Closing in favour of #18

**Pull request closed without merging**
