### PR TITLE
Update to 1.28.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative to #36

### CODE REVIEW

**Comment by kynan** [comment]
@ocefpaf can't seem to rerun those builds. They should now pass since ecmwf_grib now exists at 1.28.0

**Comment by kmuehlbauer** [comment]
@kynan, we might need to rerender.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@kynan We need to rebuild `ecmwf_grib` with the new pinnings, too.

**Comment by kmuehlbauer** [comment]
see https://github.com/conda-forge/ecmwf_grib-feedstock/pull/41

**Pull request closed without merging**
