### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/12

Cherry-picks the changes from PR ( https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/12 ) by @jjhelmus . Resolves some conflicts with current `master`.

### CODE REVIEW

**Comment by jakirkham** [comment]
@jjhelmus , could you please take a look at this and make sure it is correct?

**Review by kynan — APPROVED** [review]

**Comment by jakirkham** [comment]
Feel free to merge this as soon as you can, @kynan . We are moving ahead with `conda-build` 2 as we speak.

**Comment by ocefpaf** [comment]
This is passing and @kynan approved. So let's get that in.

**Comment by jakirkham** [comment]
Ok, thanks.

**Pull request merged**
